version: '3'
services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    depends_on:
      - database
      - php
    links:
      - database
      - php
    volumes:
      - ./html:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
      - ./certs:/etc/ssl/your-domain.com
    ports:
      - "80:80"
      - "443:443"
  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ./html:/var/www/html
      - ./php:/etc/php/7.4/fpm/php.ini
  database:
    build:
      context: ./database
    container_name: database
    restart: always
    environment:
        - MYSQL_DATABASE=your_db
        - MYSQL_ROOT_PASSWORD=YourRootPassword
        - MYSQL_USER=your_db_user
        - MYSQL_PASSWORD=YourUserPassword
    ports:
        - "3306:3306"
    volumes:
        - /dbdata:/var/lib/mysql
volumes:
  dbdata:
